agent:
  java:
    standalone_app_name: Petclinic
    scan_all_classes: false
    scan_all_code_sources: false
  logger:
    stdout: true
application:
    name: Petclinic
    #group: custom-access-group
    #metadata: bU=<value>,contactEmail=<value>,contactName=<value>